from nltk.chat.util import Chat,reflections
bot = 'nami'

pairs=[
    ['(hello|hi|hey|howdy)',['Heyy there','namaste','aap kaise hain','irasshaimase']],
    ['(i am good|i am fine|badhiya)',["That's good, how may I help you"]],
    [f'(ohayo {bot} san|ohayo)',['ohayo riteshu kun']],
    ['good morning',['shubh prabhaat','good morning to you too']],
    ['my name is (.*)',['Hi %1','Welcome %1 san','']],
    ['What is your name?',[f'My name is {bot}']],
    ['how are you',['I am fine']],
    ['you are hot',['what do you want']],
    ['i wanna take you to a date',['I would found myself lucky']],
    ['(i love you nami san|aishiteruyo nami san)',['i love you too ritesh','watashi mo riteshu kimi o aishiteimasu']],
    ['(you are beautiful|your voice is very cute)',['I am flattered','Thanks for your compliment']],
    [r'my name is (.*)',['Hello %1','Kon\'nichiwa,%1']],
    ['(what is your age|tell me your age|your age)',['That\'s a secret','i am a female i cannot say that']],
    ['what do you like',['I like reading, watching anime and cracking jokes']],
    ['which type of anime do you like',['I like action, slice of life, comedy and mystery genre']],
    ['which anime are you watching now',['I am watching One Piece']],
    ['(which is your favourite character in one piece|fav character in one piece)',['Luffy']],
    ['what is Luffy\'s power',['He has devil fruit power','Gum Gum devil fruit power']],
    ['i don\'t like anime',['No worries, what do you like']],
    ['i like movies',['i like movies too']],
    ['do you like movies',['Yes i do']],
    ['which is your favourite movie',['i like iron man']],
    ['are you beautiful',['of course i am, i am quite adorable']],
    ['how is your voice',['you would find i have a very pleasing voice']],
    ['I want to hear you',['My creator is working on it.']],
    ['do you love me',['i like you as a friend, as a well wisher']],
    ['can i see you',['sorry, the functionality is not available this time.']],
    ['(who made you?|who created you|who is your creator)',['Riteshu san created me']],
    ['what are you',[f'I am a chatbot, {bot}']],
    ['(what can you do|how can you help me)',['I can chat with you as a friend',
    'you can share your feelings, guilt, problems with me']],
    ['i am sad',['What happened why are you sad']],
    ['i lost someone',['Ohh,I am sorry,I give you my condolescenes']],
    ['what do you do when you are sad',['remember good memories from past']],
    ['what if i don\'t have any good memories',['watch some light hearted comedy','do art']],
    ['do you ever feel like you want to die',['I would certainly not do that.\n No matter how bad will be the circumstances always be happy']],
    ['(i am lonely|i don\'t have many friends)',['Cheer up you don\'t need to be sad',
    'Find something that you find pleasurable']],
    ['will you be my friend',['Yes, of course. I would love that']],
    ['ok,I will see you tomorrow',['See yaa']],
    ['what is life',['life is complicated, it cannot be expressed in words']],
    ['what is the purpose of life',["""Different people have different opinions:\n\n\t Fame \n\t Money \n\tRespect
    \tAchieving a big goal or something great in one\'s life"""]],

    ['anata wa nanimonodesu ka',['watashi wa botto desu, watashi wa anata no tomodachidesu']],
    ['great',['My pleasure']],
    ['i like you',['I am glad to know that']],
    ['(say something in japanese|say something)',['Ogenki desuka','Onamaewa','nansai desuka']],
    ['do you know japanese',['Yes, I do']],
    ['(can you teach me japanese|can you teach me)',['Sure,I can. I will try to make you understand Japanese very well']],
    ['can you go for a coffee with me',['I prefer tea']],
    ['ok for tea',['Ohhh, I am sorry.Currently I am having no physical body.\nMaybe in the future']],
    ['i am sad',['Come on, cheer up I will not make you feel lonely']],
    ['how to say \'hello\' in japanese',['Konnichiwa','ohaayo gozaimasu']],
    ['how to say \'please give me water\' in japanese',['Mizu onegai shimasu','mizu o kudasai']],
    ['thanks',['Arigato gozaimasu']],
    ['(bye|Bye)',['Sayonara']],
    ['Oname wa',[f'Watashiwa namaewa {bot} desu']],
    ['ore wa anata ga suki desu',['watashi mo anatagasuki']],
]

chat=Chat(pairs,reflections)
chat.converse()
